name: .NET (build & publish release)

on:
  push:
    tags:
    - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
    - name: Install latest .NET 6 SDK.
      uses: Elskom/setup-latest-dotnet@main
      with:
        VERSION_MAJOR: 6
        VERSION_BAND: 4xx

    - name: Restore, Build, Pack, and Push
      uses: Elskom/build-dotnet@main
      with:
        PUSH: false
    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: Shipping
        path: artifacts/packages/Release/Shipping/*
  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
    # To ensure that the current version being pushed does not get pruned we prune first.
    - name: Prune all older versions.
      uses: smartsquaregmbh/delete-old-packages@master
      with:
        keep: 0
        names: |
            Microsoft.EntityFrameworkCore.Sdk
            Microsoft.EntityFrameworkCore.App.Ref
            Microsoft.EntityFrameworkCore.App.Runtime.win-x86
            Microsoft.EntityFrameworkCore.App.Runtime.win-x64
            Microsoft.EntityFrameworkCore.App.Runtime.win-arm64
            Microsoft.EntityFrameworkCore.App.Runtime.linux-x64
            Microsoft.EntityFrameworkCore.App.Runtime.linux-arm
            Microsoft.EntityFrameworkCore.App.Runtime.linux-arm64
            Microsoft.EntityFrameworkCore.App.Runtime.osx-x64
            Microsoft.EntityFrameworkCore.App.Runtime.osx-arm64
    - name: Download artifacts
      uses: actions/download-artifact@main
      with:
        name: Shipping
        path: artifacts/packages/Release/Shipping/
    - name: Push nuget Packages to GitHub Packages.
      # we must skip the symbol packages.
      run: dotnet nuget push **/*.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }} -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate --no-symbols
    - uses: ncipollo/release-action@main
      with:
        artifacts: "artifacts/packages/Release/Shipping/*.exe,artifacts/packages/Release/Shipping/efcore-shared-framework*.pkg,artifacts/packages/Release/Shipping/*.nupkg,artifacts/packages/Release/Shipping/efcore-shared-framework*.zip,artifacts/packages/Release/Shipping/efcore-shared-framework*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
