name: .NET (build pull request)

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
    - name: Install latest .NET SDK.
      uses: Elskom/setup-latest-dotnet@main
      with:
        SDK_VERSION: '7.0.100'
        RUNTIME_VERSIONS: ''
    - name: Install debuild and fpm.
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install devscripts -y
        sudo apt-get install ruby -y
        sudo gem install fpm
    - name: Restore, Build, and Pack
      uses: Elskom/build-dotnet@main

    - name: Upload binlog on failure.
      uses: actions/upload-artifact@main
      # if: ${{ failure() }}
      with:
        name: msbuild.binlog
        path: msbuild.binlog
